[workspace]
name = "birdweather"
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
python = ">=3.14.3,<3.15"
polars = ">=1.38.1,<2"
altair = ">=6.0.0,<7"
seaborn = ">=0.13.2,<0.14"
matplotlib = ">=3.10.8,<4"
requests = ">=2.32.5,<3"
python-dotenv = ">=1.2.1,<2"
jupyter = ">=1.1.1,<2"
vl-convert-python = ">=2.0.0rc1,<3"
